import './globals.css'
import { Rubik } from 'next/font/google'
import type { Metadata } from 'next'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nextjs App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
